package me.vacuity.ai.sdk.openai.responses.entity;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import me.vacuity.ai.sdk.openai.responses.request.ResponseReasoning;
import me.vacuity.ai.sdk.openai.responses.request.ResponseTextConfig;

import java.util.List;
import java.util.Map;

/**
 * Response object from the Responses API.
 *
 * @author: vacuity
 * @create: 2025-01-22
 **/
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Response {

    /**
     * Unique identifier for this Response.
     */
    private String id;

    /**
     * The object type. Always "response".
     */
    private String object;

    /**
     * Unix timestamp (in seconds) of when this Response was created.
     */
    @JsonProperty("created_at")
    private Long createdAt;

    /**
     * Unix timestamp (in seconds) of when this Response was completed.
     */
    @JsonProperty("completed_at")
    private Long completedAt;

    /**
     * The status of the response.
     * One of "completed", "failed", "in_progress", "cancelled", "queued", or "incomplete".
     */
    private String status;

    /**
     * Model ID used to generate the response.
     */
    private String model;

    /**
     * An array of content items generated by the model.
     */
    private List<ResponseOutputItem> output;

    /**
     * The instructions provided in the request.
     */
    private Object instructions;

    /**
     * Details about why the response is incomplete.
     */
    @JsonProperty("incomplete_details")
    private IncompleteDetails incompleteDetails;

    /**
     * An error object returned when the model fails to generate a Response.
     */
    private ResponseError error;

    /**
     * Usage statistics for the response.
     */
    private ResponseUsage usage;

    /**
     * Set of key-value pairs attached to this object.
     */
    private Map<String, String> metadata;

    /**
     * What sampling temperature was used.
     */
    private Float temperature;

    /**
     * The top_p value used.
     */
    @JsonProperty("top_p")
    private Float topP;

    /**
     * An upper bound for the number of tokens generated.
     */
    @JsonProperty("max_output_tokens")
    private Integer maxOutputTokens;

    /**
     * The unique ID of the previous response to the model.
     */
    @JsonProperty("previous_response_id")
    private String previousResponseId;

    /**
     * Whether to allow the model to run tool calls in parallel.
     */
    @JsonProperty("parallel_tool_calls")
    private Boolean parallelToolCalls;

    /**
     * The truncation strategy used.
     */
    private String truncation;

    /**
     * How the model selected which tool(s) to use.
     */
    @JsonProperty("tool_choice")
    private Object toolChoice;

    /**
     * The tools available to the model.
     */
    private List<Object> tools;

    /**
     * The service tier used to process the request.
     */
    @JsonProperty("service_tier")
    private String serviceTier;

    /**
     * Whether the response was run in the background.
     */
    private Boolean background;

    /**
     * Whether the response was stored for later retrieval.
     */
    private Boolean store;

    /**
     * The conversation this response belongs to.
     */
    private Object conversation;

    /**
     * Configuration options used for the text response.
     */
    private ResponseTextConfig text;

    /**
     * Configuration options used for reasoning.
     */
    private ResponseReasoning reasoning;

    /**
     * The maximum number of total calls to built-in tools for this response.
     */
    @JsonProperty("max_tool_calls")
    private Integer maxToolCalls;

    /**
     * The number of most likely tokens returned per output token position.
     */
    @JsonProperty("top_logprobs")
    private Integer topLogprobs;

    /**
     * The prompt cache key provided in the request.
     */
    @JsonProperty("prompt_cache_key")
    private String promptCacheKey;

    /**
     * The safety identifier provided in the request.
     */
    @JsonProperty("safety_identifier")
    private String safetyIdentifier;

    /**
     * Get the text content from the first output message.
     */
    public String getOutputText() {
        if (output == null || output.isEmpty()) {
            return null;
        }
        for (ResponseOutputItem item : output) {
            if ("message".equals(item.getType()) && item.getContent() != null) {
                for (ResponseOutputContent content : item.getContent()) {
                    if ("output_text".equals(content.getType()) && content.getText() != null) {
                        return content.getText();
                    }
                }
            }
        }
        return null;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class IncompleteDetails {
        /**
         * The reason why the response is incomplete.
         * Can be "max_output_tokens" or "content_filter".
         */
        private String reason;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class ResponseError {
        /**
         * The error code.
         */
        private String code;

        /**
         * The error message.
         */
        private String message;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class ResponseUsage {
        /**
         * Number of tokens in the input.
         */
        @JsonProperty("input_tokens")
        private Integer inputTokens;

        /**
         * Number of tokens in the output.
         */
        @JsonProperty("output_tokens")
        private Integer outputTokens;

        /**
         * Total number of tokens used.
         */
        @JsonProperty("total_tokens")
        private Integer totalTokens;

        /**
         * Details about input token usage.
         */
        @JsonProperty("input_tokens_details")
        private TokenDetails inputTokensDetails;

        /**
         * Details about output token usage.
         */
        @JsonProperty("output_tokens_details")
        private TokenDetails outputTokensDetails;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class TokenDetails {
        /**
         * Number of cached tokens.
         */
        @JsonProperty("cached_tokens")
        private Integer cachedTokens;

        /**
         * Number of reasoning tokens.
         */
        @JsonProperty("reasoning_tokens")
        private Integer reasoningTokens;

        /**
         * Number of text tokens.
         */
        @JsonProperty("text_tokens")
        private Integer textTokens;
    }
}
